# Generated by Django 3.2 on 2022-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePieces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='product_img')),
            ],
        ),
    ]
