# Generated by Django 3.2 on 2022-01-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simmonopoly', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
