# Generated by Django 3.2 on 2022-01-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simmonopoly', '0004_auto_20220131_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaUser',
        ),
    ]
