# Generated by Django 3.2.12 on 2022-02-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simmonopoly', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePieces',
        ),
    ]
